//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AircrewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AircrewResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.AircrewResource", typeof(AircrewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 飞行记录设置 的本地化字符串。
        /// </summary>
        public static string Btn_FlyHistory {
            get {
                return ResourceManager.GetString("Btn_FlyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部别 的本地化字符串。
        /// </summary>
        public static string DgHeader_Department {
            get {
                return ResourceManager.GetString("DgHeader_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入伍时间 的本地化字符串。
        /// </summary>
        public static string DgHeader_EnlistmentTime {
            get {
                return ResourceManager.GetString("DgHeader_EnlistmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string DgHeader_FlyerDate {
            get {
                return ResourceManager.GetString("DgHeader_FlyerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行时间 的本地化字符串。
        /// </summary>
        public static string DgHeader_FlyerTime {
            get {
                return ResourceManager.GetString("DgHeader_FlyerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行机种 的本地化字符串。
        /// </summary>
        public static string DgHeader_FlyerType {
            get {
                return ResourceManager.GetString("DgHeader_FlyerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职别 的本地化字符串。
        /// </summary>
        public static string DgHeader_JobTitle {
            get {
                return ResourceManager.GetString("DgHeader_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string DgHeader_Name {
            get {
                return ResourceManager.GetString("DgHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 民族 的本地化字符串。
        /// </summary>
        public static string DgHeader_Native {
            get {
                return ResourceManager.GetString("DgHeader_Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string DgHeader_Sex {
            get {
                return ResourceManager.GetString("DgHeader_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞机机种： 的本地化字符串。
        /// </summary>
        public static string Lab_AircraftType {
            get {
                return ResourceManager.GetString("Lab_AircraftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础学院： 的本地化字符串。
        /// </summary>
        public static string Lab_BasicCollege {
            get {
                return ResourceManager.GetString("Lab_BasicCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毕业日期： 的本地化字符串。
        /// </summary>
        public static string Lab_BasicCollegeGraduatedTime {
            get {
                return ResourceManager.GetString("Lab_BasicCollegeGraduatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生日期： 的本地化字符串。
        /// </summary>
        public static string Lab_BirthDay {
            get {
                return ResourceManager.GetString("Lab_BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疗养信息 的本地化字符串。
        /// </summary>
        public static string Lab_Convalescent {
            get {
                return ResourceManager.GetString("Lab_Convalescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文化程度： 的本地化字符串。
        /// </summary>
        public static string Lab_Degree {
            get {
                return ResourceManager.GetString("Lab_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部别： 的本地化字符串。
        /// </summary>
        public static string Lab_Department {
            get {
                return ResourceManager.GetString("Lab_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不适等级 的本地化字符串。
        /// </summary>
        public static string Lab_DiscomfortLevel {
            get {
                return ResourceManager.GetString("Lab_DiscomfortLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入伍时间： 的本地化字符串。
        /// </summary>
        public static string Lab_EnlistmentTime {
            get {
                return ResourceManager.GetString("Lab_EnlistmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行事故 的本地化字符串。
        /// </summary>
        public static string Lab_FlightAccident {
            get {
                return ResourceManager.GetString("Lab_FlightAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行学院： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyCollege {
            get {
                return ResourceManager.GetString("Lab_FlyCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毕业日期： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyCollegeGraduatedTime {
            get {
                return ResourceManager.GetString("Lab_FlyCollegeGraduatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行记录： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyHistory {
            get {
                return ResourceManager.GetString("Lab_FlyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开飞日期： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyTime {
            get {
                return ResourceManager.GetString("Lab_FlyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行时间： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyTotalTime {
            get {
                return ResourceManager.GetString("Lab_FlyTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职别： 的本地化字符串。
        /// </summary>
        public static string Lab_JobTitle {
            get {
                return ResourceManager.GetString("Lab_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次体检时间 的本地化字符串。
        /// </summary>
        public static string Lab_LastExamDate {
            get {
                return ResourceManager.GetString("Lab_LastExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外出就医 的本地化字符串。
        /// </summary>
        public static string Lab_MedicalTreatment {
            get {
                return ResourceManager.GetString("Lab_MedicalTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 军衔： 的本地化字符串。
        /// </summary>
        public static string Lab_MilitaryRank {
            get {
                return ResourceManager.GetString("Lab_MilitaryRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名： 的本地化字符串。
        /// </summary>
        public static string Lab_Name {
            get {
                return ResourceManager.GetString("Lab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 民族： 的本地化字符串。
        /// </summary>
        public static string Lab_Native {
            get {
                return ResourceManager.GetString("Lab_Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入党时间： 的本地化字符串。
        /// </summary>
        public static string Lab_PartyTime {
            get {
                return ResourceManager.GetString("Lab_PartyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大体检 的本地化字符串。
        /// </summary>
        public static string Lab_PhysicalExamMax {
            get {
                return ResourceManager.GetString("Lab_PhysicalExamMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小体检 的本地化字符串。
        /// </summary>
        public static string Lab_PhysicalExamMin {
            get {
                return ResourceManager.GetString("Lab_PhysicalExamMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 籍贯： 的本地化字符串。
        /// </summary>
        public static string Lab_PlaceOfOrigin {
            get {
                return ResourceManager.GetString("Lab_PlaceOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登记日期： 的本地化字符串。
        /// </summary>
        public static string Lab_RecordDate {
            get {
                return ResourceManager.GetString("Lab_RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写日期： 的本地化字符串。
        /// </summary>
        public static string Lab_RecordTime {
            get {
                return ResourceManager.GetString("Lab_RecordTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别： 的本地化字符串。
        /// </summary>
        public static string Lab_Sex {
            get {
                return ResourceManager.GetString("Lab_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除飞行职务
        ///时间及原因，
        ///批准时间、机
        ///关及批件号 的本地化字符串。
        /// </summary>
        public static string Lab_Summary {
            get {
                return ResourceManager.GetString("Lab_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话： 的本地化字符串。
        /// </summary>
        public static string Lab_TelNo {
            get {
                return ResourceManager.GetString("Lab_TelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个人员！ 的本地化字符串。
        /// </summary>
        public static string Msg_NoSelect {
            get {
                return ResourceManager.GetString("Msg_NoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能选择一个人员！ 的本地化字符串。
        /// </summary>
        public static string Msg_SelectOverflow {
            get {
                return ResourceManager.GetString("Msg_SelectOverflow", resourceCulture);
            }
        }
    }
}
