//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AviationMedicineResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AviationMedicineResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.AviationMedicineResource", typeof(AviationMedicineResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话 的本地化字符串。
        /// </summary>
        public static string DgHeader_ContactTel {
            get {
                return ResourceManager.GetString("DgHeader_ContactTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毕业院校 的本地化字符串。
        /// </summary>
        public static string DgHeader_GraduatedSchool {
            get {
                return ResourceManager.GetString("DgHeader_GraduatedSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string DgHeader_Name {
            get {
                return ResourceManager.GetString("DgHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人资质 的本地化字符串。
        /// </summary>
        public static string DgHeader_PersonQualification {
            get {
                return ResourceManager.GetString("DgHeader_PersonQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业 的本地化字符串。
        /// </summary>
        public static string DgHeader_Professional {
            get {
                return ResourceManager.GetString("DgHeader_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string DgHeader_Sex {
            get {
                return ResourceManager.GetString("DgHeader_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从业日期 的本地化字符串。
        /// </summary>
        public static string DgHeader_WorkDate {
            get {
                return ResourceManager.GetString("DgHeader_WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话： 的本地化字符串。
        /// </summary>
        public static string Lab_ContactTel {
            get {
                return ResourceManager.GetString("Lab_ContactTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毕业院校： 的本地化字符串。
        /// </summary>
        public static string Lab_GraduatedSchool {
            get {
                return ResourceManager.GetString("Lab_GraduatedSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名： 的本地化字符串。
        /// </summary>
        public static string Lab_Name {
            get {
                return ResourceManager.GetString("Lab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人资质： 的本地化字符串。
        /// </summary>
        public static string Lab_PersonQualification {
            get {
                return ResourceManager.GetString("Lab_PersonQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业： 的本地化字符串。
        /// </summary>
        public static string Lab_Professional {
            get {
                return ResourceManager.GetString("Lab_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别： 的本地化字符串。
        /// </summary>
        public static string Lab_Sex {
            get {
                return ResourceManager.GetString("Lab_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从业日期： 的本地化字符串。
        /// </summary>
        public static string Lab_WorkDate {
            get {
                return ResourceManager.GetString("Lab_WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要删除的数据！ 的本地化字符串。
        /// </summary>
        public static string Msg_NoCheckedRemove {
            get {
                return ResourceManager.GetString("Msg_NoCheckedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要删除吗？ 的本地化字符串。
        /// </summary>
        public static string Msg_RemoveConfirm {
            get {
                return ResourceManager.GetString("Msg_RemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从业日期不能为空！ 的本地化字符串。
        /// </summary>
        public static string Msg_WorkDateEmpty {
            get {
                return ResourceManager.GetString("Msg_WorkDateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        public static string Radio_Female {
            get {
                return ResourceManager.GetString("Radio_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        public static string Radio_Male {
            get {
                return ResourceManager.GetString("Radio_Male", resourceCulture);
            }
        }
    }
}
