//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlightDiscomfortLevelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlightDiscomfortLevelResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.FlightDiscomfortLevelResource", typeof(FlightDiscomfortLevelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 责任医师： 的本地化字符串。
        /// </summary>
        public static string Lab_AviationMedicine {
            get {
                return ResourceManager.GetString("Lab_AviationMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主诉情况： 的本地化字符串。
        /// </summary>
        public static string Lab_Complained {
            get {
                return ResourceManager.GetString("Lab_Complained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查： 的本地化字符串。
        /// </summary>
        public static string Lab_Examination {
            get {
                return ResourceManager.GetString("Lab_Examination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行日期： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyDate {
            get {
                return ResourceManager.GetString("Lab_FlyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机型： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyerType {
            get {
                return ResourceManager.GetString("Lab_FlyerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行高度： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyHeight {
            get {
                return ResourceManager.GetString("Lab_FlyHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行速度： 的本地化字符串。
        /// </summary>
        public static string Lab_FlySpeed {
            get {
                return ResourceManager.GetString("Lab_FlySpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行科目： 的本地化字符串。
        /// </summary>
        public static string Lab_FlySubject {
            get {
                return ResourceManager.GetString("Lab_FlySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行总时间： 的本地化字符串。
        /// </summary>
        public static string Lab_FlyTotalTime {
            get {
                return ResourceManager.GetString("Lab_FlyTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 措施： 的本地化字符串。
        /// </summary>
        public static string Lab_Measure {
            get {
                return ResourceManager.GetString("Lab_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气象条件： 的本地化字符串。
        /// </summary>
        public static string Lab_WeatherCondition {
            get {
                return ResourceManager.GetString("Lab_WeatherCondition", resourceCulture);
            }
        }
    }
}
