//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InternalMedicineResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalMedicineResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.InternalMedicineResource", typeof(InternalMedicineResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 腹部： 的本地化字符串。
        /// </summary>
        public static string Lab_Abdomen {
            get {
                return ResourceManager.GetString("Lab_Abdomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血压： 的本地化字符串。
        /// </summary>
        public static string Lab_BloodPressure {
            get {
                return ResourceManager.GetString("Lab_BloodPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结论： 的本地化字符串。
        /// </summary>
        public static string Lab_Conclusion {
            get {
                return ResourceManager.GetString("Lab_Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发育情况： 的本地化字符串。
        /// </summary>
        public static string Lab_Development {
            get {
                return ResourceManager.GetString("Lab_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断： 的本地化字符串。
        /// </summary>
        public static string Lab_Diagnosis {
            get {
                return ResourceManager.GetString("Lab_Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心脏： 的本地化字符串。
        /// </summary>
        public static string Lab_Heart {
            get {
                return ResourceManager.GetString("Lab_Heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肾脏： 的本地化字符串。
        /// </summary>
        public static string Lab_Kidney {
            get {
                return ResourceManager.GetString("Lab_Kidney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肝脏： 的本地化字符串。
        /// </summary>
        public static string Lab_Liver {
            get {
                return ResourceManager.GetString("Lab_Liver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肺脏： 的本地化字符串。
        /// </summary>
        public static string Lab_Lungs {
            get {
                return ResourceManager.GetString("Lab_Lungs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 淋巴结： 的本地化字符串。
        /// </summary>
        public static string Lab_LymphGland {
            get {
                return ResourceManager.GetString("Lab_LymphGland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主诉及既往病史： 的本地化字符串。
        /// </summary>
        public static string Lab_MedicalHistory {
            get {
                return ResourceManager.GetString("Lab_MedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脉搏： 的本地化字符串。
        /// </summary>
        public static string Lab_Pulse {
            get {
                return ResourceManager.GetString("Lab_Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （休息三分钟后） 的本地化字符串。
        /// </summary>
        public static string Lab_Rest {
            get {
                return ResourceManager.GetString("Lab_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮肤： 的本地化字符串。
        /// </summary>
        public static string Lab_Skin {
            get {
                return ResourceManager.GetString("Lab_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脾脏： 的本地化字符串。
        /// </summary>
        public static string Lab_Spleen {
            get {
                return ResourceManager.GetString("Lab_Spleen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （下蹲十五次） 的本地化字符串。
        /// </summary>
        public static string Lab_Squat {
            get {
                return ResourceManager.GetString("Lab_Squat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （静止） 的本地化字符串。
        /// </summary>
        public static string Lab_Static {
            get {
                return ResourceManager.GetString("Lab_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议： 的本地化字符串。
        /// </summary>
        public static string Lab_Suggestion {
            get {
                return ResourceManager.GetString("Lab_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甲状腺： 的本地化字符串。
        /// </summary>
        public static string Lab_Thyroid {
            get {
                return ResourceManager.GetString("Lab_Thyroid", resourceCulture);
            }
        }
    }
}
