//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.MainResource", typeof(MainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要退出吗？ 的本地化字符串。
        /// </summary>
        public static string Msg_ExitConfirm {
            get {
                return ResourceManager.GetString("Msg_ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二飞行训练团健康登记管理系统 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分析统计 的本地化字符串。
        /// </summary>
        public static string ToolBar_Analysis {
            get {
                return ResourceManager.GetString("ToolBar_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航医信息 的本地化字符串。
        /// </summary>
        public static string ToolBar_AviationMedicine {
            get {
                return ResourceManager.GetString("ToolBar_AviationMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常见病 的本地化字符串。
        /// </summary>
        public static string ToolBar_CommonDisease {
            get {
                return ResourceManager.GetString("ToolBar_CommonDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不适等级 的本地化字符串。
        /// </summary>
        public static string ToolBar_DiscomfortLevel {
            get {
                return ResourceManager.GetString("ToolBar_DiscomfortLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞行事故 的本地化字符串。
        /// </summary>
        public static string ToolBar_FlightAccident {
            get {
                return ResourceManager.GetString("ToolBar_FlightAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外出就医 的本地化字符串。
        /// </summary>
        public static string ToolBar_MedicalTreatment {
            get {
                return ResourceManager.GetString("ToolBar_MedicalTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空勤人员 的本地化字符串。
        /// </summary>
        public static string ToolBar_PersonRegister {
            get {
                return ResourceManager.GetString("ToolBar_PersonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大体检 的本地化字符串。
        /// </summary>
        public static string ToolBar_PhysicalExamMax {
            get {
                return ResourceManager.GetString("ToolBar_PhysicalExamMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小体检 的本地化字符串。
        /// </summary>
        public static string ToolBar_PhysicalExamMin {
            get {
                return ResourceManager.GetString("ToolBar_PhysicalExamMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疗养信息 的本地化字符串。
        /// </summary>
        public static string ToolBar_RecuperationInformation {
            get {
                return ResourceManager.GetString("ToolBar_RecuperationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 体检提醒 的本地化字符串。
        /// </summary>
        public static string ToolBar_Remind {
            get {
                return ResourceManager.GetString("ToolBar_Remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疗养院 的本地化字符串。
        /// </summary>
        public static string ToolBar_Sanatorium {
            get {
                return ResourceManager.GetString("ToolBar_Sanatorium", resourceCulture);
            }
        }
    }
}
