//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NeuropsychiatryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NeuropsychiatryResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.NeuropsychiatryResource", typeof(NeuropsychiatryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 植物神经系统： 的本地化字符串。
        /// </summary>
        public static string Lab_AutonomicNervousSystem {
            get {
                return ResourceManager.GetString("Lab_AutonomicNervousSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 医师： 的本地化字符串。
        /// </summary>
        public static string Lab_AviationMedicine {
            get {
                return ResourceManager.GetString("Lab_AviationMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脑神经： 的本地化字符串。
        /// </summary>
        public static string Lab_CranialNerve {
            get {
                return ResourceManager.GetString("Lab_CranialNerve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断结论： 的本地化字符串。
        /// </summary>
        public static string Lab_DiagnosisConclusion {
            get {
                return ResourceManager.GetString("Lab_DiagnosisConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主诉及既往病史： 的本地化字符串。
        /// </summary>
        public static string Lab_MedicalHistory {
            get {
                return ResourceManager.GetString("Lab_MedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精神状态： 的本地化字符串。
        /// </summary>
        public static string Lab_Mentality {
            get {
                return ResourceManager.GetString("Lab_Mentality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四肢协调动作： 的本地化字符串。
        /// </summary>
        public static string Lab_MovementsOfLimbs {
            get {
                return ResourceManager.GetString("Lab_MovementsOfLimbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神经感觉： 的本地化字符串。
        /// </summary>
        public static string Lab_NeuralSensation {
            get {
                return ResourceManager.GetString("Lab_NeuralSensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查日期： 的本地化字符串。
        /// </summary>
        public static string Lab_RecordDate {
            get {
                return ResourceManager.GetString("Lab_RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静态： 的本地化字符串。
        /// </summary>
        public static string Lab_Static {
            get {
                return ResourceManager.GetString("Lab_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议： 的本地化字符串。
        /// </summary>
        public static string Lab_Suggestion {
            get {
                return ResourceManager.GetString("Lab_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肌腱反射： 的本地化字符串。
        /// </summary>
        public static string Lab_TendonReflex {
            get {
                return ResourceManager.GetString("Lab_TendonReflex", resourceCulture);
            }
        }
    }
}
