//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OphthalmologyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OphthalmologyResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.OphthalmologyResource", typeof(OphthalmologyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 医师： 的本地化字符串。
        /// </summary>
        public static string Lab_AviationMedicine {
            get {
                return ResourceManager.GetString("Lab_AviationMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色觉： 的本地化字符串。
        /// </summary>
        public static string Lab_ColorVision {
            get {
                return ResourceManager.GetString("Lab_ColorVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结论： 的本地化字符串。
        /// </summary>
        public static string Lab_Conclusion {
            get {
                return ResourceManager.GetString("Lab_Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲光间质： 的本地化字符串。
        /// </summary>
        public static string Lab_ConvolutedStroma {
            get {
                return ResourceManager.GetString("Lab_ConvolutedStroma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲光： 的本地化字符串。
        /// </summary>
        public static string Lab_CurveLight {
            get {
                return ResourceManager.GetString("Lab_CurveLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诊断： 的本地化字符串。
        /// </summary>
        public static string Lab_DiagnosisConclusion {
            get {
                return ResourceManager.GetString("Lab_DiagnosisConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远视力： 的本地化字符串。
        /// </summary>
        public static string Lab_DistantVision {
            get {
                return ResourceManager.GetString("Lab_DistantVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 眼球： 的本地化字符串。
        /// </summary>
        public static string Lab_Eyeball {
            get {
                return ResourceManager.GetString("Lab_Eyeball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 眼底： 的本地化字符串。
        /// </summary>
        public static string Lab_EyeBellow {
            get {
                return ResourceManager.GetString("Lab_EyeBellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 眼睑，结膜： 的本地化字符串。
        /// </summary>
        public static string Lab_Eyelid {
            get {
                return ResourceManager.GetString("Lab_Eyelid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐斜： 的本地化字符串。
        /// </summary>
        public static string Lab_Heterophoria {
            get {
                return ResourceManager.GetString("Lab_Heterophoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （左） 的本地化字符串。
        /// </summary>
        public static string Lab_Left {
            get {
                return ResourceManager.GetString("Lab_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主诉及既往病史： 的本地化字符串。
        /// </summary>
        public static string Lab_MedicalHistory {
            get {
                return ResourceManager.GetString("Lab_MedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 近视力： 的本地化字符串。
        /// </summary>
        public static string Lab_NearVision {
            get {
                return ResourceManager.GetString("Lab_NearVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜间视力： 的本地化字符串。
        /// </summary>
        public static string Lab_NightVision {
            get {
                return ResourceManager.GetString("Lab_NightVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离识别： 的本地化字符串。
        /// </summary>
        public static string Lab_RangeRecognition {
            get {
                return ResourceManager.GetString("Lab_RangeRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （右） 的本地化字符串。
        /// </summary>
        public static string Lab_Right {
            get {
                return ResourceManager.GetString("Lab_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议： 的本地化字符串。
        /// </summary>
        public static string Lab_Suggestion {
            get {
                return ResourceManager.GetString("Lab_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视力： 的本地化字符串。
        /// </summary>
        public static string Lab_Vision {
            get {
                return ResourceManager.GetString("Lab_Vision", resourceCulture);
            }
        }
    }
}
