//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecuperationInformationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public RecuperationInformationResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.RecuperationInformationResource", typeof(RecuperationInformationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Btn_Setup {
            get {
                return ResourceManager.GetString("Btn_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话 的本地化字符串。
        /// </summary>
        public static string DgHeader_ContactTel {
            get {
                return ResourceManager.GetString("DgHeader_ContactTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string DgHeader_Name {
            get {
                return ResourceManager.GetString("DgHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员安排： 的本地化字符串。
        /// </summary>
        public static string Lab_Aviation {
            get {
                return ResourceManager.GetString("Lab_Aviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细地址： 的本地化字符串。
        /// </summary>
        public static string Lab_DetailAddress {
            get {
                return ResourceManager.GetString("Lab_DetailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划出院日期： 的本地化字符串。
        /// </summary>
        public static string Lab_DischargeDatePlan {
            get {
                return ResourceManager.GetString("Lab_DischargeDatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划入院日期： 的本地化字符串。
        /// </summary>
        public static string Lab_HospitalizationDatePlan {
            get {
                return ResourceManager.GetString("Lab_HospitalizationDatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带队领导： 的本地化字符串。
        /// </summary>
        public static string Lab_Leader {
            get {
                return ResourceManager.GetString("Lab_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 责任医师： 的本地化字符串。
        /// </summary>
        public static string Lab_ResponsibilityMedicine {
            get {
                return ResourceManager.GetString("Lab_ResponsibilityMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疗养院： 的本地化字符串。
        /// </summary>
        public static string Lab_Sanatorium {
            get {
                return ResourceManager.GetString("Lab_Sanatorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疗养院电话： 的本地化字符串。
        /// </summary>
        public static string Lab_SanatoriumTelNumber {
            get {
                return ResourceManager.GetString("Lab_SanatoriumTelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随行人员： 的本地化字符串。
        /// </summary>
        public static string Lab_SupplementsMember {
            get {
                return ResourceManager.GetString("Lab_SupplementsMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出行方式： 的本地化字符串。
        /// </summary>
        public static string Lab_TripMode {
            get {
                return ResourceManager.GetString("Lab_TripMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择疗养人员！ 的本地化字符串。
        /// </summary>
        public static string Msg_NoAircrew {
            get {
                return ResourceManager.GetString("Msg_NoAircrew", resourceCulture);
            }
        }
    }
}
