//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInfomation.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SupplementaryExamResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SupplementaryExamResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthyInfomation.Resource.SupplementaryExamResource", typeof(SupplementaryExamResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 血糖: 的本地化字符串。
        /// </summary>
        public static string Lab_BloodSugar {
            get {
                return ResourceManager.GetString("Lab_BloodSugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心电图: 的本地化字符串。
        /// </summary>
        public static string Lab_Cardiogram {
            get {
                return ResourceManager.GetString("Lab_Cardiogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胸部X线: 的本地化字符串。
        /// </summary>
        public static string Lab_ChestXLine {
            get {
                return ResourceManager.GetString("Lab_ChestXLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胆固醇: 的本地化字符串。
        /// </summary>
        public static string Lab_Cholesterol {
            get {
                return ResourceManager.GetString("Lab_Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 肝功能: 的本地化字符串。
        /// </summary>
        public static string Lab_LiverFunction {
            get {
                return ResourceManager.GetString("Lab_LiverFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他: 的本地化字符串。
        /// </summary>
        public static string Lab_Orther {
            get {
                return ResourceManager.GetString("Lab_Orther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血常规: 的本地化字符串。
        /// </summary>
        public static string Lab_RoutineBlood {
            get {
                return ResourceManager.GetString("Lab_RoutineBlood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 便常规: 的本地化字符串。
        /// </summary>
        public static string Lab_RoutineDefecate {
            get {
                return ResourceManager.GetString("Lab_RoutineDefecate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尿常规: 的本地化字符串。
        /// </summary>
        public static string Lab_RoutineUrine {
            get {
                return ResourceManager.GetString("Lab_RoutineUrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甘油三脂: 的本地化字符串。
        /// </summary>
        public static string Lab_Trilaurin {
            get {
                return ResourceManager.GetString("Lab_Trilaurin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B超: 的本地化字符串。
        /// </summary>
        public static string Lab_Ultrasonic {
            get {
                return ResourceManager.GetString("Lab_Ultrasonic", resourceCulture);
            }
        }
    }
}
