//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInformation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircrew
    {
        public int TransactionNumber { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Sex { get; set; }
        public string Nation { get; set; }
        public string Photo { get; set; }
        public string Degree { get; set; }
        public System.DateTime EnlistmentTime { get; set; }
        public System.DateTime PartyTime { get; set; }
        public string NativePlace { get; set; }
        public string TroopsType { get; set; }
        public string TroopsTel { get; set; }
        public string JobTitle { get; set; }
        public string MilitaryRank { get; set; }
        public System.DateTime GraduationJuniorDate { get; set; }
        public System.DateTime GraduationDate { get; set; }
        public System.DateTime PilotPlaneDate { get; set; }
        public string TerminateContractDetail { get; set; }
        public System.DateTime InDate { get; set; }
        public string InUser { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string LastEditUser { get; set; }
        public string AdmissionJuniorCollege { get; set; }
        public string AdmissionCollege { get; set; }
    }
}
