//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInformation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightDiscomfortLevel
    {
        public int TransactionNumber { get; set; }
        public System.DateTime FlyDate { get; set; }
        public string FlySubject { get; set; }
        public decimal FlyHeight { get; set; }
        public int FlyerType { get; set; }
        public decimal FlySpeed { get; set; }
        public decimal FlyTotalTime { get; set; }
        public string WeatherCondition { get; set; }
        public string Complained { get; set; }
        public string Examination { get; set; }
        public string Measure { get; set; }
        public int AviationMedicineID { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string InUser { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string LastEditUser { get; set; }
    }
}
