//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInformation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalTreatment
    {
        public int TransactionNumber { get; set; }
        public int AircrewID { get; set; }
        public System.DateTime HospitalizationDate { get; set; }
        public System.DateTime DischargeDate { get; set; }
        public string HospitalLocation { get; set; }
        public string HospitalReason { get; set; }
        public string CheckSituation { get; set; }
        public string Diagnosis { get; set; }
        public string Conclusion { get; set; }
        public string NeedObservation { get; set; }
        public Nullable<System.DateTime> ObservationStartDate { get; set; }
        public Nullable<System.DateTime> ObservationEndDate { get; set; }
        public System.DateTime InDate { get; set; }
        public string InUser { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string LastEditUser { get; set; }
        public System.DateTime RecordDate { get; set; }
    }
}
