//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInformation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neuropsychiatry
    {
        public int TransactionNumber { get; set; }
        public string MedicalHistory { get; set; }
        public string Psychosis { get; set; }
        public string CranialNerve { get; set; }
        public string MovementsOfLimbs { get; set; }
        public string Quiescent { get; set; }
        public string TendonReflex { get; set; }
        public string NerveEnding { get; set; }
        public string VegetativeNerve { get; set; }
        public string DiagnosisConclusion { get; set; }
        public string Suggestion { get; set; }
        public int AviationMedicineID { get; set; }
        public System.DateTime InDate { get; set; }
        public string InUser { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string LastEditUser { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int AircrewID { get; set; }
    }
}
