//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInformation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phthalmology
    {
        public int TransactionNumber { get; set; }
        public int AircrewID { get; set; }
        public string VisionLeft { get; set; }
        public string VisionRight { get; set; }
        public string NearVisionLeft { get; set; }
        public string NearVisionRight { get; set; }
        public string DistantVisionLeft { get; set; }
        public string DistantVisionRight { get; set; }
        public string CurveLightLeft { get; set; }
        public string CurveLightRight { get; set; }
        public string Heterophoria { get; set; }
        public string ColorVision { get; set; }
        public string RangeRecognition { get; set; }
        public string MedicalHistory { get; set; }
        public string Eyelid { get; set; }
        public string Eyeball { get; set; }
        public string ConvolutedStroma { get; set; }
        public string EyeBellow { get; set; }
        public string NightVision { get; set; }
        public string DiagnosisConclusion { get; set; }
        public string Suggestion { get; set; }
        public int AviationMedicineID { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string InUser { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string LastEditUser { get; set; }
    }
}
