//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInformation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecuperationInformation
    {
        public RecuperationInformation()
        {
            this.RecuperationAccompany = new HashSet<RecuperationAccompany>();
            this.RecuperationMember = new HashSet<RecuperationMember>();
        }
    
        public int TransactionNumber { get; set; }
        public int SanatoriumID { get; set; }
        public System.DateTime HospitalEnterDate { get; set; }
        public System.DateTime HospitalLeaveDate { get; set; }
        public Nullable<int> LeaderAircrewID { get; set; }
        public Nullable<int> AviationMedicineID { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public string InUser { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string LastEditUser { get; set; }
    
        public virtual ICollection<RecuperationAccompany> RecuperationAccompany { get; set; }
        public virtual ICollection<RecuperationMember> RecuperationMember { get; set; }
    }
}
