//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyInformation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplementaryExam
    {
        public int TransactionNumber { get; set; }
        public string RoutineBlood { get; set; }
        public string RoutineUrine { get; set; }
        public string RoutineDefecate { get; set; }
        public string LiverFunction { get; set; }
        public string BloodSugar { get; set; }
        public string Cholesterol { get; set; }
        public string Trilaurin { get; set; }
        public string Cardiogram { get; set; }
        public string ChestXLine { get; set; }
        public string Ultrasonic { get; set; }
        public string Other { get; set; }
        public int AircrewID { get; set; }
        public System.DateTime InDate { get; set; }
        public string InUser { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string LastEditUser { get; set; }
    }
}
